sudo: required

services:
  - docker

before_install:
- docker pull atejeda/openjfx-el
- docker run --rm -w /root/workspace -v $PWD:/root/workspace atejeda/openjfx-el scl enable devtoolset-3 'make info deps all'
- docker ps -a